[project]
name = "camera-object-dection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.12.0.88",
    "torch>=2.8.0",
    "triton>=3.4.0",
    "ultralytics>=8.3.176",
]
